language: python

matrix:
  include:
    - os: linux
    - os: osx
      before_install:
        - brew update
        - brew install python
        - brew install python3


python:
  - 2.7
  - 3.6
script: python test-travisTest.py
